name: Deploy to droplet

on:
    push:
        branches:
            - main

jobs:
    deploys:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                node-version: '18'

            - name: Install npm dependencies
              run: npm install

            - name: Create build
              run: npm run build # build files will be in "dist" directory

            - name: Delete remote files and upload new files
              uses: appleboy/scp-action@master
              with:
                host: |
                  ${{ secrets.REMOTE_HOST }}
                username: ${{ secrets.REMOTE_USER }}
                port: ${{ secrets.REMOTE_PORT }}
                key: |
                  ${{ secrets.SSH_PRIVATE_KEY }}
                source: "dist"
                target: ${{ secrets.REMOTE_DIR_PATH }}
                rm: true # removes existing files
                debug: true
                strip_components: 1 # this transfers everything IN dist, but not dist itself

            - name: Purge CloudFlare cache
              uses: nathanvaughn/actions-cloudflare-purge@master
              with:
                cf_zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}
                cf_auth: ${{ secrets.CLOUDFLARE_API_KEY }}
