name: Deploy to server

on:
    push:
        branches:
            - main

jobs:
    deploys:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Initiate Node
              uses: actions/setup-node@v2
              with:
                node-version: '18'

            - name: Install npm dependencies
              run: npm install

            # build files into "./public" directory
            - name: Build from vite into "./public" directory
              run: npm run build

            - name: SSH test
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: 167.71.94.115
                username: ${{ secrets.REMOTE_USER }}
                password: ${{ secrets.REMOTE_PASS }}
                port: ${{ secrets.REMOTE_PORT }}
                script: |
                  whoami
                  ls -al

            - name: Delete remote files and upload new files
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.REMOTE_HOST }}
                username: ${{ secrets.REMOTE_USER }}
                port: ${{ secrets.REMOTE_PORT }}
                # key: ${{ secrets.SSH_PRIVATE_KEY }}
                password: ${{ secrets.REMOTE_PASS }}
                source: "public/*"
                target: ${{ secrets.REMOTE_DIR_PATH }}
                rm: true
                debug: true
